# Generated by Django 3.2.8 on 2021-10-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [migrations.RunSQL('ALTER TABLE contacts_contact AUTO_INCREMENT = 256;')
    ]
