version: '3'

services:
  db:
    image: postgres:15
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    ports:
      - '5432:5432'
    volumes:
      - ./django_postgres:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.d
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
    healthcheck:
      test: "exit 0"
  web:
    build: .
    command: >
      sh -c "
            python manage.py collectstatic
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py loaddata contacts/fixtures/contacts.json &&
            python manage.py loaddata contacts/fixtures/auth_groups.json &&
            python manage.py loaddata contacts/fixtures/animals.json &&
            python manage.py loaddata contacts/fixtures/breeds.json &&
            python manage.py loaddata contacts/fixtures/pets.json &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/django-contacts/
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
