dog_breeds = [
    "Labrador Retriever",
    "French Bulldog",
    "German Shepherd",
    "Golden Retriever",
    "Bulldog",
    "Poodle",
    "Beagle",
    "Rottweiler",
    "German Shorthaired Pointer",
    "Dachshund",
    "Pembroke Welsh Corgi",
    "Australian Shepherd",
    "Yorkshire Terrier",
    "Boxer",
    "Great Dane",
    "Siberian Husky",
    "Cavalier King Charles Spaniel",
    "Doberman Pinscher",
    "Shih Tzu",
    "Miniature Schnauzer",
    "Boston Terrier",
    "Bernese Mountain Dog",
    "Pomeranian",
    "Havanese",
    "Cane Corso",
    "Shetland Sheepdog",
    "Brittany",
    "English Springer Spaniel",
    "Cocker Spaniel",
    "Belgian Malinois",
    "Pug",
    "Border Collie",
    "Basset Hound",
    "Mastiff",
    "Chihuahua",
    "Vizsla",
    "Bloodhound",
    "Weimaraner",
    "Collie",
    "Newfoundland",
    "West Highland White Terrier",
    "Shiba Inu",
    "Rhodesian Ridgeback",
    "Bull Terrier",
    "American Staffordshire Terrier",
    "Alaskan Malamute",
    "Soft Coated Wheaten Terrier",
    "Airedale Terrier",
    "Akita",
    "Staffordshire Bull Terrier"
]